version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: school-docker/backend/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./school-backend:/var/www/html
      - './school-docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - backend
      - frontend
  backend:
    build: 
      context: .
      dockerfile: school-docker/backend/php.dockerfile
    volumes:
      - ./school-backend:/var/www/html:delegated
      - /var/www/html/storage
    depends_on:
      - mysql
  frontend:
    build:
      context: .
      dockerfile: school-docker/frontend/dev.dockerfile
    ports:
      - '3000:3000'
      - "24678:24678"
    volumes:
      - ./school-frontend:/usr/src/app 
      - /usr/src/app/node_modules 
  mysql:
    image: 'mysql:5.7'
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - ./school-docker/env/mysql.env
        
  composer:
    build: 
      context: .
      dockerfile: school-docker/backend/composer.dockerfile
    volumes:
      - ./school-backend:/var/www/html
  artisan:
    build: 
      context: .
      dockerfile: school-docker/backend/php.dockerfile
    volumes:
      - ./school-backend:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]  
  # npm:
  #   image: node:14
  #   working_dir: /
volumes:
  mysql-data:

